### ISSUE TITLE
Hide containers not in the Allowed list

### ISSUE THREAD

**Issue by chris3081** [Assaro/DD_Bot#21]
Any chance you could add the ability to hide the containers not in allowed list? happy to submit a PR if you like

**Comment by Assaro** [comment]
You mean display only the containers in the allowedContainers list? This is true for everyone who isn't an admin. Would be an easy fix. 
I am however currently working on a complete rewrite of  all the permissions. I will probably not add anything like that to the current version. I may add it to the new iteration. You can check it out by using the dev image from docker. It should be fully working. Please save your settings before trying it.

**Comment by chris3081** [comment]
Perfect, for the moment I've dropped the admins into the users list and that will sort things for me in the short term thanks.
