### ISSUE TITLE
display the container IP.

### ISSUE THREAD

**Issue by 0xabdoulaye** [Assaro/DD_Bot#36]
Hey can you add an functionality to display the started container IP on the discord bot

**Comment by Assaro** [comment]
Sorry for the late answer. Did not see notifications regarding your Issue. The IP of the container can be seen using the command on the host machine: `inspect --format '{{range networkSettings}}ContainerIPv4Address{{end}}' <container_name>`

**Comment by Assaro** [comment]
I have also just added it to show the ip on startup. You should be able to see it in the log once i have published a new version
