### ISSUE TITLE
Bot always disconnects after a second without error

### ISSUE THREAD

**Issue by pigeon-paddy** [Assaro/DD_Bot#40]
After inputting Token and starting Container again I get the following output
![Screenshot 2024-11-19 175655](https://github.com/user-attachments/assets/9d2dded4-71c8-4e9f-86bd-7d307ea40da6)

I tried resetting the token, deleting the app and recreating it under a different name, recreating the whole container and decreasing the number of displayed containers down to 1.
![Screenshot 2024-11-19 175927](https://github.com/user-attachments/assets/b6d7ec0b-7970-4496-b078-0744f80d6c44)

When creating and starting the container for the first time I get the output "Invalid Token", but once I put it in settings file, the warning doesn´t appear anymore, so I guess my Token is right.
Maybe some firewall issue? Do I need to specify ports? If so, which ports does dc expect?

Thanks for your help!
I would love to get this running :D

**Comment by pigeon-paddy** [comment]
adding ports: - "443:443" to yaml file and open ports in firewall doesn´t change my results

**Comment by Assaro** [comment]
Hey,
this is a new one. I am assuming you do not have problems with either slow or spotty internet.
First: You don't need any open Port or other type of firewall exclusion. 
Second: Please send me your settings.json (remove the token and your Discord UID!!)
Additionally, please compare what privileges you have granted the bot on your server (https://github.com/Assaro/DD_Bot/raw/master/pics/BotPermissions.png)

**Comment by pigeon-paddy** [comment]
Thanks for your response!
No my internet is fine..
The permissions are exactly the same, even attempted to just give full admin rights.
The token should be written between "" right? Or "<>"?

Cheers Patrick

{
  "LanguageSettings": {
    "Language": "en"
  },
  "DiscordSettings": {
    "Token": "",
    "AdminIDs": [
      
    ],
    "UserWhitelist": true,
    "UserIDs": [],
    "UsersCanStopContainers": false,
    "AllowedContainers": [],
    "RoleStartPermissions": {},
    "RoleStopPermissions": {},
    "UserStartPermissions": {},
    "UserStopPermissions": {}
  },
  "DockerSettings": {
    "BotName": "DD_Bot",
    "Retries": 6,
    "TimeBeforeRetry": 5,
    "ContainersPerMessage": 1
  }
}

**Comment by Assaro** [comment]
Settings seem fine. The reconnects to Discord have to occur because of Session Timeout stuff with Discord's API.
If they actually happen multiple times a minute sth is off, but seeing the message in your log is to be expected. Does the Bot work even though those messages appear? If so, then it is fine to ignore it

**Comment by pigeon-paddy** [comment]
The only time it connects to dc is when I manually add it to the server via the link from dev.dc, then it disconnects pretty much instantly, but I could just paste the link again to try again. 
It doesn´t reconnect by itself!
Therefore, sadly no commands are possible

**Comment by Assaro** [comment]
This is truely odd. You should only have to add it once. Then you start it and are good to go.
I have had some issues with Discord's API before. Therefore I would like to ask you to just shut it off for now and wait like a few hours. I have had weird Problems with commands not working and connection issues just go away after some time, especially after using a new Bot. If that doesn't work we will have to look deeper.

**Comment by pigeon-paddy** [comment]
Alright. The dc interface was updated since your release, 
and I could get install links over "OAuth2" (like you) & "Installation" tab.

![Screenshot 2024-11-20 002710](https://github.com/user-attachments/assets/16516ffb-1b29-42bc-8034-c7b9238c7000)
I've tried both.

**Comment by pigeon-paddy** [comment]
Hey, after a few days it still doesn´t work at all.
I might just do something essential wrong..

**Comment by Assaro** [comment]
Welp, that's just the way it is sometimes. Best thing is to figure it out with a discord call. Please add me (assaro_delamar)
and i will message you after work, approximately 8:30pm gmt+1

**Comment by Assaro** [comment]
Solved: Problem not related to this Project
