### ISSUE TITLE
Request returns failed when it actually succeeded 

### ISSUE THREAD

**Issue by TyPilot** [Assaro/DD_Bot#6]
Priority: low
Impact: UI/user communication 
Issue:
When running the command `/docker dockername:CONTAINER_NAME command:stop`, the request returns that it was not able to stop the server. However, when checking `/list`, it has indeed stopped. 

![SmartSelect_20221015_101347_Discord](https://user-images.githubusercontent.com/7003699/195994194-272d75ab-5b04-4b63-9b83-d2ed65000c89.jpg)

**Comment by Assaro** [comment]
This does happen on large containers right now, as the Time between the stop command and the status check is currently hardcoded to five seconds. I will fix that soon, probably with a small subroutine to give it several tries.

**Comment by Assaro** [comment]
Fixed in latest commit #7

**Comment by TyPilot** [comment]
Awesome! I'm assuming I just restart the bot for the update to take affect? Thanks!
